stages:
	- test
	- build
	- deploy

before_script:
	- go get github.com/kardianos/govendor
	- mkdir -p $GOPATH/src/github.com/yuri-karkh/gr && cd "$_"
	- govendor init
	- govendor fetch github.com/gin-gonic/gin@v1.2

test:
	stage: test
	script:
		- go test -v -cover

build:
	stage: build
	script: 
		- go build
			
deploy_staging:
	stage: deploy
	script:
		- echo "Deploy to staging server"
	environment:
		name: staging
		url: https://go-staging.gentlereader.com
	only:
		- staging

deploy_prod:
	stage: deploy
	script:
		- echo "Deploy to production server"
	environment:
		name: production
		url: https://go.gentlereader.com
		when: manual
	only:
		- tag